language: php

php:
- 7.2

before_script:
- composer config -g github-oauth.github.com $GITHUB_ACCESS_TOKEN
- composer self-update
- composer require codeclimate/php-test-reporter --dev
- composer install --prefer-dist --no-interaction


after_script:
- vendor/bin/test-reporter

after_script:
- vendor/bin/test-reporter --stdout > codeclimate.json
- "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v1.0.1-dev)' https://codeclimate.com/test_reports"
